[2023-12-19T19:37:58.902+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_dwh.sat_employee_social_performance_update manual__2023-12-19T19:37:45.217017+00:00 [queued]>
[2023-12-19T19:37:58.912+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_dwh.sat_employee_social_performance_update manual__2023-12-19T19:37:45.217017+00:00 [queued]>
[2023-12-19T19:37:58.912+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-19T19:37:58.929+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): sat_employee_social_performance_update> on 2023-12-19 19:37:45.217017+00:00
[2023-12-19T19:37:58.937+0000] {standard_task_runner.py:57} INFO - Started process 1043 to run task
[2023-12-19T19:37:58.941+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'update_dwh', 'sat_employee_social_performance_update', 'manual__2023-12-19T19:37:45.217017+00:00', '--job-id', '378', '--raw', '--subdir', 'DAGS_FOLDER/update_dwh_dag.py', '--cfg-path', '/tmp/tmpbhpl8_kc']
[2023-12-19T19:37:58.944+0000] {standard_task_runner.py:85} INFO - Job 378: Subtask sat_employee_social_performance_update
[2023-12-19T19:37:58.994+0000] {task_command.py:416} INFO - Running <TaskInstance: update_dwh.sat_employee_social_performance_update manual__2023-12-19T19:37:45.217017+00:00 [running]> on host 5e0c64ad45d7
[2023-12-19T19:37:59.091+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_dwh' AIRFLOW_CTX_TASK_ID='sat_employee_social_performance_update' AIRFLOW_CTX_EXECUTION_DATE='2023-12-19T19:37:45.217017+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-19T19:37:45.217017+00:00'
[2023-12-19T19:37:59.092+0000] {sql.py:274} INFO - Executing: 
INSERT INTO rdv.sat_employee_social_performance
SELECT DISTINCT
	md5(so.employeenumber::text),
	'csv',
	now() ,
	so.environmentsatisfaction,
	so.jobsatisfaction,
	so.relationshipsatisfaction,
	so.worklifebalance
FROM
    staging.stg_table so
LEFT OUTER JOIN rdv.sat_employee_social_performance sat ON (sat.employee_hash_key = md5(so.employeenumber::text) AND sat.created_at IS NULL)
where 
	coalesce(so.environmentsatisfaction, 0) != coalesce(sat.environment_satisfaction, 0) or
	coalesce(so.jobsatisfaction, 0) != coalesce(sat.job_satisfaction, 0) or
	coalesce(so.relationshipsatisfaction, 0) != coalesce(sat.relationship_satisfaction, 0) or
	coalesce(so.worklifebalance, 0) != coalesce(sat.work_life_balance, 0)
[2023-12-19T19:37:59.101+0000] {base.py:73} INFO - Using connection ID 'stg_conn' for task execution.
[2023-12-19T19:37:59.102+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/connection.py:374: AirflowProviderDeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
  return hook_class(**{hook.connection_id_attribute_name: self.conn_id}, **hook_params)

[2023-12-19T19:37:59.110+0000] {base.py:73} INFO - Using connection ID 'stg_conn' for task execution.
[2023-12-19T19:37:59.177+0000] {sql.py:418} INFO - Running statement: 
INSERT INTO rdv.sat_employee_social_performance
SELECT DISTINCT
	md5(so.employeenumber::text),
	'csv',
	now() ,
	so.environmentsatisfaction,
	so.jobsatisfaction,
	so.relationshipsatisfaction,
	so.worklifebalance
FROM
    staging.stg_table so
LEFT OUTER JOIN rdv.sat_employee_social_performance sat ON (sat.employee_hash_key = md5(so.employeenumber::text) AND sat.created_at IS NULL)
where 
	coalesce(so.environmentsatisfaction, 0) != coalesce(sat.environment_satisfaction, 0) or
	coalesce(so.jobsatisfaction, 0) != coalesce(sat.job_satisfaction, 0) or
	coalesce(so.relationshipsatisfaction, 0) != coalesce(sat.relationship_satisfaction, 0) or
	coalesce(so.worklifebalance, 0) != coalesce(sat.work_life_balance, 0), parameters: None
[2023-12-19T19:37:59.204+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "sat_employee_social_performance_pk"
DETAIL:  Key (employee_hash_key, created_at)=(4a2ddf148c5a9c42151a529e8cbdcc06, 2023-12-19 19:37:59.163619+00) already exists.

[2023-12-19T19:37:59.214+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=update_dwh, task_id=sat_employee_social_performance_update, execution_date=20231219T193745, start_date=20231219T193758, end_date=20231219T193759
[2023-12-19T19:37:59.232+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 378 for task sat_employee_social_performance_update (duplicate key value violates unique constraint "sat_employee_social_performance_pk"
DETAIL:  Key (employee_hash_key, created_at)=(4a2ddf148c5a9c42151a529e8cbdcc06, 2023-12-19 19:37:59.163619+00) already exists.
; 1043)
[2023-12-19T19:37:59.277+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-19T19:37:59.290+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
