[2023-11-26T11:01:41.633+0000] {processor.py:157} INFO - Started process (PID=29) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:01:41.634+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:01:41.636+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:01:41.635+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:01:41.639+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:01:41.638+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:01:41.640+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:01:41.659+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.029 seconds
[2023-11-26T11:02:12.458+0000] {processor.py:157} INFO - Started process (PID=87) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:02:12.461+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:02:12.463+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:02:12.463+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:02:12.465+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:02:12.464+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:02:12.465+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:02:12.477+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:02:42.596+0000] {processor.py:157} INFO - Started process (PID=143) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:02:42.596+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:02:42.597+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:02:42.597+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:02:42.599+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:02:42.598+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:02:42.599+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:02:42.611+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-26T11:03:12.633+0000] {processor.py:157} INFO - Started process (PID=201) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:03:12.634+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:03:12.636+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:03:12.636+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:03:12.638+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:03:12.638+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:03:12.639+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:03:12.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-26T11:03:42.951+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:03:42.951+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:03:42.953+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:03:42.953+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:03:42.955+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:03:42.955+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:03:42.956+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:03:42.967+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-26T11:04:13.144+0000] {processor.py:157} INFO - Started process (PID=315) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:04:13.147+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:04:13.149+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:04:13.148+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:04:13.150+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:04:13.150+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:04:13.151+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:04:13.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-26T11:04:43.333+0000] {processor.py:157} INFO - Started process (PID=372) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:04:43.334+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:04:43.335+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:04:43.335+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:04:43.337+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:04:43.336+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:04:43.337+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:04:43.350+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-26T11:05:13.420+0000] {processor.py:157} INFO - Started process (PID=429) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:05:13.423+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:05:13.425+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:05:13.425+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:05:13.428+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:05:13.427+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:05:13.428+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:05:13.442+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.026 seconds
[2023-11-26T11:05:43.529+0000] {processor.py:157} INFO - Started process (PID=486) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:05:43.532+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:05:43.533+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:05:43.533+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:05:43.535+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:05:43.534+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:05:43.535+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:05:43.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:06:13.799+0000] {processor.py:157} INFO - Started process (PID=542) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:06:13.801+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:06:13.803+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:06:13.803+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:06:13.805+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:06:13.804+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:06:13.805+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:06:13.817+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:06:43.846+0000] {processor.py:157} INFO - Started process (PID=599) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:06:43.849+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:06:43.851+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:06:43.850+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:06:43.852+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:06:43.852+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:06:43.853+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:06:43.866+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-26T11:07:13.897+0000] {processor.py:157} INFO - Started process (PID=656) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:07:13.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:07:13.902+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:07:13.902+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:07:13.904+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:07:13.903+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:07:13.904+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:07:13.916+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-26T11:07:44.143+0000] {processor.py:157} INFO - Started process (PID=712) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:07:44.146+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:07:44.147+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:07:44.147+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:07:44.149+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:07:44.149+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:07:44.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:07:44.163+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-26T11:08:14.211+0000] {processor.py:157} INFO - Started process (PID=769) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:08:14.214+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:08:14.216+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:08:14.216+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:08:14.219+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:08:14.218+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:08:14.219+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:08:14.232+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-26T11:08:44.617+0000] {processor.py:157} INFO - Started process (PID=827) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:08:44.620+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:08:44.621+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:08:44.621+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:08:44.623+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:08:44.623+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:08:44.623+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:08:44.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-26T11:09:14.705+0000] {processor.py:157} INFO - Started process (PID=884) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:09:14.705+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:09:14.707+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:09:14.707+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:09:14.709+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:09:14.708+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:09:14.709+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:09:14.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:09:44.880+0000] {processor.py:157} INFO - Started process (PID=941) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:09:44.883+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:09:44.884+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:09:44.884+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:09:44.886+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:09:44.885+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:09:44.886+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:09:44.899+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-26T11:10:15.024+0000] {processor.py:157} INFO - Started process (PID=998) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:10:15.026+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:10:15.030+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:10:15.029+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:10:15.035+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:10:15.033+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:10:15.036+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:10:15.063+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.045 seconds
[2023-11-26T11:10:45.090+0000] {processor.py:157} INFO - Started process (PID=1055) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:10:45.093+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:10:45.094+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:10:45.094+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:10:45.097+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:10:45.096+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:10:45.097+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:10:45.109+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-26T11:11:15.129+0000] {processor.py:157} INFO - Started process (PID=1112) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:11:15.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:11:15.131+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:11:15.131+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:11:15.133+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:11:15.132+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:11:15.133+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:11:15.147+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:11:45.241+0000] {processor.py:157} INFO - Started process (PID=1169) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:11:45.244+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:11:45.245+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:11:45.245+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:11:45.247+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:11:45.246+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:11:45.247+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:11:45.259+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:12:15.302+0000] {processor.py:157} INFO - Started process (PID=1226) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:12:15.304+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:12:15.306+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:12:15.305+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:12:15.307+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:12:15.307+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:12:15.307+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:12:15.319+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-26T11:12:45.359+0000] {processor.py:157} INFO - Started process (PID=1283) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:12:45.362+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:12:45.363+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:12:45.363+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:12:45.365+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:12:45.364+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:12:45.365+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:12:45.378+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:13:16.228+0000] {processor.py:157} INFO - Started process (PID=1341) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:13:16.229+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:13:16.231+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:13:16.231+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:13:16.233+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:13:16.232+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:13:16.233+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:13:16.246+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:13:47.075+0000] {processor.py:157} INFO - Started process (PID=1399) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:13:47.077+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:13:47.078+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:13:47.078+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:13:47.080+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:13:47.080+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:13:47.080+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:13:47.093+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:14:17.136+0000] {processor.py:157} INFO - Started process (PID=1456) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:14:17.139+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:14:17.140+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:14:17.140+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:14:17.142+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:14:17.141+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:14:17.142+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:14:17.154+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:14:47.173+0000] {processor.py:157} INFO - Started process (PID=1514) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:14:47.176+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:14:47.178+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:14:47.177+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:14:47.180+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:14:47.179+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:14:47.180+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:14:47.191+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-26T11:15:18.085+0000] {processor.py:157} INFO - Started process (PID=1571) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:15:18.088+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:15:18.089+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:15:18.089+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:15:18.091+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:15:18.091+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:15:18.091+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:15:18.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:15:48.992+0000] {processor.py:157} INFO - Started process (PID=1628) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:15:48.993+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:15:48.994+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:15:48.994+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:15:48.995+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:15:48.995+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:15:48.996+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:15:49.008+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.017 seconds
[2023-11-26T11:16:19.600+0000] {processor.py:157} INFO - Started process (PID=1685) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:16:19.602+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:16:19.603+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:16:19.603+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:16:19.605+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:16:19.605+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:16:19.605+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:16:19.618+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:16:49.884+0000] {processor.py:157} INFO - Started process (PID=1742) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:16:49.885+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:16:49.886+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:16:49.886+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:16:49.888+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:16:49.887+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:16:49.888+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:16:49.899+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.017 seconds
[2023-11-26T11:17:20.690+0000] {processor.py:157} INFO - Started process (PID=1799) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:17:20.692+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:17:20.693+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:17:20.693+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:17:20.695+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:17:20.695+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:17:20.695+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:17:20.708+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:17:50.925+0000] {processor.py:157} INFO - Started process (PID=1856) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:17:50.927+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:17:50.928+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:17:50.928+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:17:50.930+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:17:50.929+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:17:50.930+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:17:50.943+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:18:21.171+0000] {processor.py:157} INFO - Started process (PID=1913) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:18:21.172+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:18:21.173+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:18:21.173+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:18:21.175+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:18:21.174+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:18:21.175+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:18:21.187+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-26T11:18:51.973+0000] {processor.py:157} INFO - Started process (PID=1970) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:18:51.975+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:18:51.977+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:18:51.976+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:18:51.978+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:18:51.978+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:18:51.979+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:18:51.990+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:19:22.130+0000] {processor.py:157} INFO - Started process (PID=2027) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:19:22.131+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:19:22.132+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:19:22.132+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:19:22.134+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:19:22.133+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:19:22.134+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:19:22.146+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-26T11:19:52.448+0000] {processor.py:157} INFO - Started process (PID=2084) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:19:52.450+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:19:52.451+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:19:52.451+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:19:52.453+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:19:52.452+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:19:52.453+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:19:52.464+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:20:22.887+0000] {processor.py:157} INFO - Started process (PID=2141) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:20:22.888+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:20:22.889+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:20:22.889+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:20:22.890+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:20:22.890+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:20:22.891+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:20:22.903+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-26T11:20:53.740+0000] {processor.py:157} INFO - Started process (PID=2198) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:20:53.743+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:20:53.744+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:20:53.744+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:20:53.746+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:20:53.745+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:20:53.746+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:20:53.758+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:21:24.681+0000] {processor.py:157} INFO - Started process (PID=2255) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:21:24.684+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:21:24.685+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:21:24.685+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:21:24.687+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:21:24.686+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:21:24.687+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:21:24.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-26T11:21:55.537+0000] {processor.py:157} INFO - Started process (PID=2312) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:21:55.538+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:21:55.540+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:21:55.540+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:21:55.542+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:21:55.542+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:21:55.542+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:21:55.555+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-26T11:22:26.335+0000] {processor.py:157} INFO - Started process (PID=2369) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:22:26.337+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:22:26.338+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:22:26.338+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:22:26.340+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:22:26.340+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:22:26.340+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:22:26.353+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:22:57.217+0000] {processor.py:157} INFO - Started process (PID=2427) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:22:57.220+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:22:57.221+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:22:57.221+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:22:57.223+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:22:57.223+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:22:57.223+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:22:57.236+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:23:28.097+0000] {processor.py:157} INFO - Started process (PID=2484) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:23:28.098+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:23:28.100+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:23:28.099+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:23:28.101+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:23:28.101+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:23:28.102+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:23:28.114+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-26T11:23:58.985+0000] {processor.py:157} INFO - Started process (PID=2542) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:23:58.988+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:23:58.989+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:23:58.989+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:23:58.991+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:23:58.990+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:23:58.991+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:23:59.002+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-26T11:24:29.899+0000] {processor.py:157} INFO - Started process (PID=2599) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:24:29.901+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:24:29.902+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:24:29.902+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:24:29.904+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:24:29.904+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:24:29.904+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:24:29.917+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:25:00.847+0000] {processor.py:157} INFO - Started process (PID=2656) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:25:00.849+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:25:00.851+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:25:00.851+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:25:00.852+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:25:00.852+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:25:00.853+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:25:00.866+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:28:11.293+0000] {processor.py:157} INFO - Started process (PID=2719) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:28:11.294+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:28:11.296+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:28:11.296+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:28:11.298+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:28:11.298+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:28:11.299+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:28:11.331+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.040 seconds
[2023-11-26T11:28:41.738+0000] {processor.py:157} INFO - Started process (PID=2777) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:28:41.739+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:28:41.740+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:28:41.740+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:28:41.742+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:28:41.741+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:28:41.742+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:28:41.754+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-26T11:29:12.588+0000] {processor.py:157} INFO - Started process (PID=2834) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:29:12.590+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:29:12.591+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:29:12.591+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:29:12.593+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:29:12.593+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:29:12.593+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:29:12.606+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:29:43.410+0000] {processor.py:157} INFO - Started process (PID=2892) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:29:43.411+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:29:43.413+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:29:43.412+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:29:43.414+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:29:43.414+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:29:43.414+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:29:43.426+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-26T11:30:14.272+0000] {processor.py:157} INFO - Started process (PID=2949) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:30:14.274+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:30:14.276+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:30:14.275+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:30:14.277+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:30:14.277+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:30:14.278+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:30:14.290+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:30:44.398+0000] {processor.py:157} INFO - Started process (PID=3006) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:30:44.399+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:30:44.401+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:30:44.401+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:30:44.403+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:30:44.402+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:30:44.403+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:30:44.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:31:15.080+0000] {processor.py:157} INFO - Started process (PID=3063) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:31:15.083+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:31:15.084+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:31:15.084+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:31:15.086+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:31:15.085+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:31:15.086+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:31:15.098+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:31:45.252+0000] {processor.py:157} INFO - Started process (PID=3120) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:31:45.252+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:31:45.253+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:31:45.253+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:31:45.255+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:31:45.255+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:31:45.255+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:31:45.267+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-26T11:32:15.357+0000] {processor.py:157} INFO - Started process (PID=3177) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:32:15.359+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:32:15.361+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:32:15.361+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:32:15.363+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:32:15.362+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:32:15.363+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:32:15.375+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:32:45.479+0000] {processor.py:157} INFO - Started process (PID=3234) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:32:45.480+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:32:45.481+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:32:45.481+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:32:45.482+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:32:45.482+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:32:45.483+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:32:45.494+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-26T11:33:15.537+0000] {processor.py:157} INFO - Started process (PID=3291) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:33:15.540+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:33:15.541+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:33:15.541+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:33:15.543+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:33:15.542+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:33:15.543+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:33:15.555+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:33:46.288+0000] {processor.py:157} INFO - Started process (PID=3348) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:33:46.291+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:33:46.292+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:33:46.292+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:33:46.294+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:33:46.293+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:33:46.294+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:33:46.306+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:34:17.032+0000] {processor.py:157} INFO - Started process (PID=3405) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:34:17.035+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:34:17.037+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:34:17.036+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:34:17.038+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:34:17.038+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:34:17.039+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:34:17.050+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-26T11:34:47.739+0000] {processor.py:157} INFO - Started process (PID=3462) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:34:47.742+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:34:47.744+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:34:47.743+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:34:47.745+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:34:47.745+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:34:47.746+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:34:47.758+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:35:18.424+0000] {processor.py:157} INFO - Started process (PID=3519) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:35:18.425+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:35:18.427+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:35:18.427+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:35:18.429+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:35:18.428+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:35:18.429+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:35:18.444+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:35:49.157+0000] {processor.py:157} INFO - Started process (PID=3576) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:35:49.160+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:35:49.162+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:35:49.162+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:35:49.164+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:35:49.163+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:35:49.164+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:35:49.176+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-26T11:36:19.942+0000] {processor.py:157} INFO - Started process (PID=3633) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:36:19.943+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:36:19.946+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:36:19.945+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:36:19.948+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:36:19.947+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:36:19.948+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:36:19.960+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-26T11:36:50.604+0000] {processor.py:157} INFO - Started process (PID=3690) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:36:50.607+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:36:50.608+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:36:50.608+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:36:50.610+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:36:50.609+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:36:50.610+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:36:50.622+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:37:21.380+0000] {processor.py:157} INFO - Started process (PID=3747) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:37:21.383+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:37:21.385+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:37:21.385+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:37:21.387+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:37:21.386+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:37:21.387+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:37:21.398+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-26T11:37:52.011+0000] {processor.py:157} INFO - Started process (PID=3804) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:37:52.013+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:37:52.015+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:37:52.015+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:37:52.017+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:37:52.016+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:37:52.017+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:37:52.030+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-26T11:38:22.699+0000] {processor.py:157} INFO - Started process (PID=3861) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:38:22.701+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:38:22.703+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:38:22.703+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:38:22.705+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:38:22.704+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:38:22.705+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:38:22.718+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:38:53.500+0000] {processor.py:157} INFO - Started process (PID=3918) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:38:53.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:38:53.504+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:38:53.504+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:38:53.506+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:38:53.506+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:38:53.506+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:38:53.519+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:39:24.195+0000] {processor.py:157} INFO - Started process (PID=3975) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:39:24.196+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:39:24.197+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:39:24.197+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:39:24.199+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:39:24.198+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:39:24.199+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:39:24.212+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-26T11:39:54.992+0000] {processor.py:157} INFO - Started process (PID=4032) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:39:54.994+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:39:54.996+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:39:54.996+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:39:54.998+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:39:54.997+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:39:54.998+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:39:55.010+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:40:25.715+0000] {processor.py:157} INFO - Started process (PID=4089) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:40:25.718+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:40:25.720+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:40:25.719+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:40:25.721+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:40:25.721+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:40:25.722+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:40:25.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:40:56.427+0000] {processor.py:157} INFO - Started process (PID=4145) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:40:56.430+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:40:56.432+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:40:56.432+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:40:56.433+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:40:56.433+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:40:56.434+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:40:56.445+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:41:27.123+0000] {processor.py:157} INFO - Started process (PID=4202) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:41:27.126+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:41:27.128+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:41:27.128+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:41:27.130+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:41:27.130+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:41:27.130+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:41:27.142+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-26T11:41:57.936+0000] {processor.py:157} INFO - Started process (PID=4259) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:41:57.939+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:41:57.941+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:41:57.941+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:41:57.942+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:41:57.942+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:41:57.943+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:41:57.955+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:42:28.718+0000] {processor.py:157} INFO - Started process (PID=4316) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:42:28.721+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:42:28.723+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:42:28.723+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:42:28.725+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:42:28.724+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:42:28.725+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:42:28.738+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-26T11:42:59.572+0000] {processor.py:157} INFO - Started process (PID=4374) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:42:59.574+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:42:59.576+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:42:59.576+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:42:59.578+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:42:59.577+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:42:59.578+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:42:59.589+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:43:29.657+0000] {processor.py:157} INFO - Started process (PID=4431) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:43:29.659+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:43:29.661+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:43:29.661+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:43:29.663+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:43:29.662+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:43:29.663+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:43:29.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-26T11:44:00.404+0000] {processor.py:157} INFO - Started process (PID=4488) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:44:00.404+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:44:00.406+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:44:00.406+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:44:00.408+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:44:00.407+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:44:00.408+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:44:00.419+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-26T11:44:31.119+0000] {processor.py:157} INFO - Started process (PID=4545) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:44:31.122+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:44:31.124+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:44:31.123+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:44:31.125+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:44:31.125+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:44:31.126+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:44:31.138+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:45:01.788+0000] {processor.py:157} INFO - Started process (PID=4602) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:45:01.790+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:45:01.792+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:45:01.792+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:45:01.794+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:45:01.793+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:45:01.794+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:45:01.807+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-26T11:45:32.419+0000] {processor.py:157} INFO - Started process (PID=4660) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:45:32.420+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:45:32.422+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:45:32.422+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:45:32.424+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:45:32.423+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:45:32.424+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:45:32.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-26T11:46:05.238+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:46:05.243+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-26T11:46:05.254+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:46:05.254+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:46:05.268+0000] {logging_mixin.py:151} INFO - [2023-11-26T11:46:05.265+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-26T11:46:05.268+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-26T11:46:05.286+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.051 seconds
